name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    name: generate-github-profile-3d-contrib

    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name id1945
          git config user.email duonghuudai.id002@gmail.com
          git add -A .
          git commit -m "Generate 3D images"
          git push
